# Generated by Django 3.2 on 2021-08-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.IntegerField(db_column='ville_id', primary_key=True, serialize=False)),
                ('departement', models.CharField(blank=True, db_column='ville_departement', max_length=3, null=True)),
                ('slug', models.CharField(blank=True, db_column='ville_slug', max_length=255, null=True)),
                ('nom', models.CharField(blank=True, db_column='ville_nom', max_length=45, null=True)),
                ('nom_simple', models.CharField(blank=True, db_column='ville_nom_simple', max_length=45, null=True)),
                ('nom_reel', models.CharField(blank=True, db_column='ville_nom_reel', max_length=45, null=True)),
                ('nom_soundex', models.CharField(blank=True, db_column='ville_nom_soundex', max_length=20, null=True)),
                ('nom_metaphone', models.CharField(blank=True, db_column='ville_nom_metaphone', max_length=22, null=True)),
                ('code_postal', models.CharField(blank=True, db_column='ville_code_postal', max_length=255, null=True)),
                ('commune', models.CharField(blank=True, db_column='ville_commune', max_length=3, null=True)),
                ('code_commune', models.CharField(db_column='ville_code_commune', max_length=5)),
                ('arrondissement', models.IntegerField(blank=True, db_column='ville_arrondissement', null=True)),
                ('canton', models.CharField(blank=True, db_column='ville_canton', max_length=4, null=True)),
                ('amdi', models.IntegerField(blank=True, db_column='ville_amdi', null=True)),
                ('population_2010', models.IntegerField(blank=True, db_column='ville_population_2010', null=True)),
                ('population_1999', models.IntegerField(blank=True, db_column='ville_population_1999', null=True)),
                ('population_2012', models.IntegerField(blank=True, db_column='ville_population_2012', null=True)),
                ('densite_2010', models.IntegerField(blank=True, db_column='ville_densite_2010', null=True)),
                ('surface', models.FloatField(blank=True, db_column='ville_surface', null=True)),
                ('longitude_deg', models.FloatField(blank=True, db_column='ville_longitude_deg', null=True)),
                ('latitude_deg', models.FloatField(blank=True, db_column='ville_latitude_deg', null=True)),
                ('longitude_grd', models.CharField(blank=True, db_column='ville_longitude_grd', max_length=9, null=True)),
                ('latitude_grd', models.CharField(blank=True, db_column='ville_latitude_grd', max_length=8, null=True)),
                ('longitude_dms', models.CharField(blank=True, db_column='ville_longitude_dms', max_length=9, null=True)),
                ('latitude_dms', models.CharField(blank=True, db_column='ville_latitude_dms', max_length=8, null=True)),
                ('zmin', models.IntegerField(blank=True, db_column='ville_zmin', null=True)),
                ('zmax', models.IntegerField(blank=True, db_column='ville_zmax', null=True)),
            ],
            options={
                'db_table': 'villes_france_free',
            },
        ),
        migrations.AddIndex(
            model_name='ville',
            index=models.Index(fields=['departement'], name='departement_idx'),
        ),
        migrations.AddIndex(
            model_name='ville',
            index=models.Index(fields=['slug'], name='slug_idx'),
        ),
        migrations.AddIndex(
            model_name='ville',
            index=models.Index(fields=['nom'], name='nom_idx'),
        ),
        migrations.AddIndex(
            model_name='ville',
            index=models.Index(fields=['nom_simple'], name='nom_simple_idx'),
        ),
        migrations.AddIndex(
            model_name='ville',
            index=models.Index(fields=['nom_reel'], name='nom_reel_idx'),
        ),
        migrations.AddIndex(
            model_name='ville',
            index=models.Index(fields=['nom_soundex'], name='nom_soundex_idx'),
        ),
        migrations.AddIndex(
            model_name='ville',
            index=models.Index(fields=['nom_metaphone'], name='nom_metaphone_idx'),
        ),
        migrations.AddIndex(
            model_name='ville',
            index=models.Index(fields=['code_postal'], name='code_postal_idx'),
        ),
        migrations.AddIndex(
            model_name='ville',
            index=models.Index(fields=['commune'], name='commune_idx'),
        ),
        migrations.AddIndex(
            model_name='ville',
            index=models.Index(fields=['code_commune'], name='code_commune_idx'),
        ),
        migrations.AddIndex(
            model_name='ville',
            index=models.Index(fields=['arrondissement'], name='arrondissement_idx'),
        ),
        migrations.AddIndex(
            model_name='ville',
            index=models.Index(fields=['canton'], name='canton_idx'),
        ),
        migrations.AddIndex(
            model_name='ville',
            index=models.Index(fields=['amdi'], name='amdi_idx'),
        ),
    ]
