# Generated by Django 3.2.6 on 2021-08-26 16:32

from pathlib import Path

from django.db import migrations
from django.core.management import call_command

from ..models import Ville

def load_villes(apps, schema_editor):
    fixtures = Path(__file__).parent / 'villes.json.gz'
    print("  Populating database...")
    Ville.objects.all().delete()  # In case of partially loaded or corrupted data
    call_command('loaddata', fixtures)

def delete_villes(app, schema_editor):
    Ville.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('villes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_villes, delete_villes),
    ]
