# Generated by Django 3.2 on 2021-08-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villes', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ville',
            index=models.Index(fields=['departement'], name='departement_idx'),
        ),
        migrations.AddIndex(
            model_name='ville',
            index=models.Index(fields=['slug'], name='slug_idx'),
        ),
        migrations.AddIndex(
            model_name='ville',
            index=models.Index(fields=['nom'], name='nom_idx'),
        ),
        migrations.AddIndex(
            model_name='ville',
            index=models.Index(fields=['nom_simple'], name='nom_simple_idx'),
        ),
        migrations.AddIndex(
            model_name='ville',
            index=models.Index(fields=['nom_reel'], name='nom_reel_idx'),
        ),
        migrations.AddIndex(
            model_name='ville',
            index=models.Index(fields=['nom_soundex'], name='nom_soundex_idx'),
        ),
        migrations.AddIndex(
            model_name='ville',
            index=models.Index(fields=['nom_metaphone'], name='nom_metaphone_idx'),
        ),
        migrations.AddIndex(
            model_name='ville',
            index=models.Index(fields=['code_postal'], name='code_postal_idx'),
        ),
        migrations.AddIndex(
            model_name='ville',
            index=models.Index(fields=['commune'], name='commune_idx'),
        ),
        migrations.AddIndex(
            model_name='ville',
            index=models.Index(fields=['code_commune'], name='code_commune_idx'),
        ),
        migrations.AddIndex(
            model_name='ville',
            index=models.Index(fields=['arrondissement'], name='arrondissement_idx'),
        ),
        migrations.AddIndex(
            model_name='ville',
            index=models.Index(fields=['canton'], name='canton_idx'),
        ),
        migrations.AddIndex(
            model_name='ville',
            index=models.Index(fields=['amdi'], name='amdi_idx'),
        ),
    ]
