# Generated by Django 3.0.4 on 2020-04-07 14:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('state', models.CharField(choices=[('A', 'En préparation'), ('B', 'Ouverte'), ('C', 'Admins'), ('D', 'Gelée'), ('E', 'Régularisation'), ('F', 'Terminée')], default='A', max_length=1)),
                ('description', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name_plural': 'Deliveries',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('auto_validate', models.BooleanField(default=False)),
                ('staff', models.ManyToManyField(related_name='staff_of_network', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Plural',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singular', models.CharField(max_length=64, unique=True)),
                ('plural', models.CharField(blank=True, default=None, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity_per_package', models.IntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=64, null=True)),
                ('quantity_limit', models.IntegerField(blank=True, null=True)),
                ('unit_weight', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=6)),
                ('quantum', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=3)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('place', models.PositiveSmallIntegerField(blank=True, default=True, null=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floreal.Delivery')),
            ],
            options={
                'ordering': ('place', '-quantity_per_package', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Subgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('auto_validate', models.BooleanField(default=False)),
                ('candidates', models.ManyToManyField(related_name='candidate_of_subgroup', through='floreal.Candidacy', to=settings.AUTH_USER_MODEL)),
                ('extra_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floreal.Network')),
                ('staff', models.ManyToManyField(related_name='staff_of_subgroup', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='user_of_subgroup', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('network', 'name')},
            },
        ),
        migrations.CreateModel(
            name='UserPhones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubgroupStateForDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('X', 'Non validé'), ('Y', 'Commande validée'), ('Z', 'Compta validée')], default='X', max_length=1)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floreal.Delivery')),
                ('subgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floreal.Subgroup')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDiscrepancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=9)),
                ('reason', models.CharField(max_length=256)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floreal.Product')),
                ('subgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floreal.Subgroup')),
            ],
            options={
                'verbose_name_plural': 'Product Discrepancies',
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('action', models.CharField(max_length=256)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryDiscrepancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('reason', models.CharField(max_length=256)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floreal.Delivery')),
                ('subgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floreal.Subgroup')),
            ],
            options={
                'verbose_name_plural': 'Delivery Discrepancies',
            },
        ),
        migrations.AddField(
            model_name='delivery',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floreal.Network'),
        ),
        migrations.AddField(
            model_name='candidacy',
            name='subgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floreal.Subgroup'),
        ),
        migrations.AddField(
            model_name='candidacy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=6)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floreal.Product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('product', 'user')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='delivery',
            unique_together={('network', 'name')},
        ),
    ]
