# Generated by Django 3.1.4 on 2021-02-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floreal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='delivery_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='freeze_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='image_description',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='network',
            name='short_description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
