# Generated by Django 3.2 on 2021-08-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floreal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='florealuser',
            name='pseudonym',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
