# Generated by Django 3.2 on 2021-08-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floreal', '0002_florealuser_pseudonym'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
