# Generated by Django 3.1.4 on 2021-03-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floreal', '0002_auto_20210221_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='close_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='distribution_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
