# Generated by Django 3.2 on 2021-09-07 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floreal', '0003_network_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='visible',
        ),
    ]
