# Generated by Django 3.1.4 on 2021-03-13 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floreal', '0003_auto_20210313_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='close_date',
            new_name='freeze_date',
        ),
        migrations.RemoveField(
            model_name='network',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='network',
            name='freeze_date',
        ),
    ]
