# Generated by Django 3.1.4 on 2021-03-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floreal', '0004_auto_20210313_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
