# Generated by Django 3.2 on 2021-09-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floreal', '0004_remove_delivery_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmessage',
            name='title',
            field=models.CharField(default='Message', max_length=80),
        ),
        migrations.AlterField(
            model_name='adminmessage',
            name='message',
            field=models.CharField(max_length=280),
        ),
    ]
