# Generated by Django 3.2.7 on 2021-09-26 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('villes', '0002_load_data'),
        ('floreal', '0005_constrain_admin_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='search_string',
            field=models.TextField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='network',
            name='ville',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='villes.ville'),
        ),
    ]
