# Generated by Django 3.2 on 2021-04-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floreal', '0006_auto_20210331_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='florealuser',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='network',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='networksubgroup',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
