# Generated by Django 3.2.7 on 2021-09-27 14:12

from django.db import migrations, models
from django.utils.timezone import now

class Migration(migrations.Migration):

    dependencies = [
        ('floreal', '0006_add_villes_and_search_strings'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=now),
            preserve_default=False,
        ),
    ]
