# Generated by Django 3.2.8 on 2021-10-11 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floreal', '0007_delivery_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkmembership',
            name='is_regulator',
        ),
    ]
