# Generated by Django 3.2 on 2021-04-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floreal', '0007_auto_20210412_1227'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='networkmembership',
            constraint=models.UniqueConstraint(fields=('network', 'user'), name='unique_membership'),
        ),
        migrations.AddConstraint(
            model_name='networksubgroup',
            constraint=models.UniqueConstraint(fields=('network', 'name'), name='unique_subgroup_name'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('delivery', 'name'), name='unique_product'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_purchase'),
        ),
    ]
