# Generated by Django 3.2 on 2021-07-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floreal', '0008_auto_20210424_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantum',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=5),
        ),
    ]
