# Generated by Django 3.2.7 on 2021-11-03 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floreal', '0009_bestof_in_db'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bestof',
            options={'ordering': ['rank']},
        ),
    ]
