# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floreal', '0009_discrepancy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discrepancy',
            options={'verbose_name_plural': 'Discrepancies'},
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
