# Generated by Django 3.2 on 2021-07-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floreal', '0009_alter_product_quantum'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='networkmembership',
            name='unique_membership',
        ),
        migrations.AddField(
            model_name='network',
            name='latitude',
            field=models.FloatField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='longitude',
            field=models.FloatField(default=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='networkmembership',
            constraint=models.UniqueConstraint(fields=('network', 'user', 'valid_until'), name='unique_membership'),
        ),
    ]
