#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floreal', '0010_add_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='place',
            field=models.PositiveSmallIntegerField(blank=True, default=True, null=True),
        ),
    ]
