# Generated by Django 3.2 on 2021-07-27 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floreal', '0010_auto_20210727_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='network',
            name='longitude',
        ),
    ]
