# Generated by Django 3.2 on 2021-07-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floreal', '0011_auto_20210727_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='latitude',
            field=models.FloatField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='longitude',
            field=models.FloatField(default=True, null=True),
        ),
    ]
