#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-11 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('floreal', '0013_product_discrepancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDiscrepancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('reason', models.CharField(max_length=256)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floreal.Delivery')),
                ('subgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floreal.Subgroup')),
            ],
            options={
                'verbose_name_plural': 'Delivery Discrepancies',
            },
        ),
        migrations.AlterModelOptions(
            name='productdiscrepancy',
            options={'verbose_name_plural': 'Product Discrepancies'},
        ),
    ]
