# Generated by Django 3.2 on 2021-07-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floreal', '0013_auto_20210727_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='florealuser',
            name='latitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='florealuser',
            name='longitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='latitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='longitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
