# Generated by Django 3.2 on 2021-08-01 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floreal', '0014_auto_20210729_0916'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_product',
        ),
    ]
