# Generated by Django 3.0.4 on 2020-03-30 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('floreal', '0014_deliverydiscrepancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='state',
            field=models.CharField(choices=[('A', 'En préparation'), ('B', 'Ouverte'), ('C', 'Admins'), ('D', 'Gelée'), ('E', 'Régularisation'), ('F', 'Terminée')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subgroup',
            name='extra_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subgroupstatefordelivery',
            name='state',
            field=models.CharField(choices=[('X', 'Non validé'), ('Y', 'Commande validée'), ('Z', 'Compta validée')], default='X', max_length=1),
        ),
    ]
