# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-24 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floreal', '0014_deliverydiscrepancy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverydiscrepancy',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='deliverydiscrepancy',
            name='subgroup',
        ),
        migrations.DeleteModel(
            name='DeliveryDiscrepancy',
        ),
    ]
