# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-05 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floreal', '0014_deliverydiscrepancy'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set([]),
        ),
    ]
