# Generated by Django 3.2 on 2021-08-05 09:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('floreal', '0015_remove_product_unique_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
