# Generated by Django 3.0.4 on 2020-04-17 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('floreal', '0016_auto_20200417_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('everyone', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('network', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='floreal.Network')),
                ('subgroup', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='floreal.Subgroup')),
            ],
        ),
    ]
