# Generated by Django 3.0.4 on 2020-04-17 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floreal', '0017_adminmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
