# Generated by Django 3.0.4 on 2020-04-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floreal', '0019_auto_20200421_1056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidacy',
            options={'verbose_name_plural': 'Candidacies'},
        ),
        migrations.AddField(
            model_name='network',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
