# Generated by Django 3.0.4 on 2020-04-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floreal', '0020_auto_20200422_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default=True, null=True, upload_to=''),
        ),
    ]
