# Generated by Django 3.0.4 on 2020-07-22 09:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('floreal', '0023_auto_20200714_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='producers',
            field=models.ManyToManyField(related_name='producer_of_network', to=settings.AUTH_USER_MODEL),
        ),
    ]
