# Generated by Django 3.0.4 on 2020-07-22 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floreal', '0024_add_producer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdiscrepancy',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productdiscrepancy',
            name='subgroup',
        ),
        migrations.DeleteModel(
            name='DeliveryDiscrepancy',
        ),
        migrations.DeleteModel(
            name='ProductDiscrepancy',
        ),
    ]
