# Generated by Django 3.0.4 on 2020-07-22 09:49

from django.conf import settings
from django.db import migrations, models
from floreal import models as m

def transfer_membership(apps, schema_editor):
    for nw in m.Network.objects.all():
        subgroups = nw.subgroup_set.all()
        if len(subgroups) > 1:
            for sg in subgroups:
                nw2 = m.Network.objects.create(
                    name = nw.name + "/" + sg.name,
                    auto_validate = nw.auto_validate,
                    description = nw.description
                )
                nw2.staff.set(nw.staff.all() | sg.staff.all())
                nw2.producers.set(nw.producers.all())
                nw2.members.set(sg.users.all())
            nw.delete()
        elif len(subgroups) == 1:
            sg = subgroups[0]
            nw.staff.add(sg.staff.all())
            nw.members.set(sg.users.all())
        else:
            print("Warning, network withoutsubgroup", repr(nw))


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('floreal', '0025_del_discrepancies'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='members',
            field=models.ManyToManyField(related_name='member_of_network', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='network',
            name='regulators',
            field=models.ManyToManyField(related_name='regulator_of_network', to=settings.AUTH_USER_MODEL),
        )
    ]
