# Generated by Django 3.0.4 on 2020-07-22 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('floreal', '0027_network_members_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='networks',
            field=models.ManyToManyField(to='floreal.Network'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='floreal.Network'),
        ),
    ]
