# Generated by Django 3.0.4 on 2020-07-22 10:35

from django.db import migrations, models
import django.db.models.deletion
from floreal import models as m


def transfer_network(apps, schema_editor):
    for dv in m.Delivery.objects.all():
        dv.networks.add(dv.network)

class Migration(migrations.Migration):

    dependencies = [
        ('floreal', '0028_add_multi_network_dv'),
    ]

    operations = [
        migrations.RunPython(transfer_network)
    ]
