# Generated by Django 3.0.4 on 2020-07-22 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floreal', '0029_transfer_dv_networks'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='delivery',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='network',
        ),
    ]
