# Generated by Django 3.0.4 on 2020-07-22 10:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('floreal', '0030_single_dv_network_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subgroup',
            name='candidates',
        ),
        migrations.AddField(
            model_name='network',
            name='candidates',
            field=models.ManyToManyField(related_name='candidate_of_network', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Candidacy',
        ),
    ]
