# Generated by Django 3.0.4 on 2020-07-22 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floreal', '0031_sg_candidacy_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subgroupstatefordelivery',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='subgroupstatefordelivery',
            name='subgroup',
        ),
        migrations.RemoveField(
            model_name='adminmessage',
            name='subgroup',
        ),
        migrations.DeleteModel(
            name='Subgroup',
        ),
        migrations.DeleteModel(
            name='SubgroupStateForDelivery',
        ),
    ]
