# Generated by Django 3.2.6 on 2021-08-26 10:45

from django.db import migrations
from ..models import TexteDAccueil
from wagtail.models import Site, Page
from django.contrib.contenttypes.models import ContentType


def create_texte_d_accueil(apps, schema_editor):
    texte_accueil = '''<h2 data-block-key="tddr5">Bienvenue</h2><p data-block-key="d6kqb">Customiser le texte d&#x27;accueil dans « administrer / Gestion du contenu rédactionnel / Pages »</p>'''
    texte_page = TexteDAccueil(
        title="Texte d'accueil",
        texte_accueil=texte_accueil,
        content_type=ContentType.objects.get_for_model(TexteDAccueil)
    )
    # root = Site.objects.get(is_default_site=True).root_page
    root = Page.get_first_root_node()
    root.add_child(instance=texte_page)


def delete_texte_d_accueil(apps, schema_editor):
    TexteDAccueil.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
        ("wagtailcore", "0066_collection_management_permissions"),
        ("wagtailsearch", "0006_customise_indexentry"),
        ("wagtailcore", "0075_populate_latest_revision_and_revision_object_str"),
    ]

    operations = [migrations.RunPython(create_texte_d_accueil, delete_texte_d_accueil)]
