# Generated by Django 3.2 on 2021-08-06 10:57

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_garecentrale'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
