# Generated by Django 3.2 on 2021-08-06 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='body',
            new_name='texte_accueil',
        ),
    ]
